version: '3.9'
services:
  database:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  messagequeue:
    image: rmohr/activemq:5.15.9
    ports:
      - 61616:61616
      - 8161:8161